language: go
go:
  - 1.16.x
  - 1.17.x
  - 1.18.x
install:
  - make dependencies
script:
  - make lint
  - make test
branches:
  only:
    - main  
after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
