CREATE TABLE "TEST    "."SOURCE"  (
		  "INT64" BIGINT , 
		  "INT32" INTEGER , 
		  "INT16" SMALLINT , 
		  "BOOL" BOOLEAN , 
		  "FLOAT64" DOUBLE , 
		  "DATE" DATE , 
		  "TIME" TIME , 
		  "TS" TIMESTAMP , 
		  "VCHAR" VARCHAR(50 OCTETS) , 
		  "CHAR" CHAR(50 OCTETS) , 
		  "DECIMAL" DECIMAL(17,3) , 
		  "real" REAL , 
		  "BLOB" BLOB(1000) LOGGED NOT COMPACT )   
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW  ;

CREATE TABLE "TEST    "."DEST"  (
		  "INT64" BIGINT , 
		  "INT32" INTEGER , 
		  "INT16" SMALLINT , 
		  "BOOL" BOOLEAN , 
		  "FLOAT64" DOUBLE , 
		  "DATE" DATE , 
		  "TIME" TIME , 
		  "TS" TIMESTAMP , 
		  "VCHAR" VARCHAR(50 OCTETS) , 
		  "CHAR" CHAR(50 OCTETS) , 
		  "DECIMAL" DECIMAL(17,3) , 
		  "real" REAL , 
		  "BLOB" BLOB(1000) LOGGED NOT COMPACT )   
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW  ;