create user test IDENTIFIED BY test;
grant connect, resource TO test;
ALTER USER TEST QUOTA UNLIMITED ON USERS;

CREATE TABLE TEST.SRC (
	T_NUM NUMBER,
	T_INT INTEGER,
	T_SINT SMALLINT,
	T_BFLOAT BINARY_FLOAT,
	T_FLOAT FLOAT,
	T_DOUBLE BINARY_DOUBLE,
	T_REAL REAL,
	T_DATE DATE,
	T_DECIMAL DECIMAL,
	T_TS TIMESTAMP,
	T_VCHAR VARCHAR(100),
	T_CHAR CHAR(100),
	T_NCHAR NCHAR(100),
	T_VCHAR2 VARCHAR2(100),
	T_NVCHAR NVARCHAR2(100),
	T_BLOB BLOB,
	T_CLOB CLOB,
	T_NCLOB NCLOB,
	T_RAW RAW(100),
	T_LR LONG RAW
);

CREATE TABLE TEST.DEST (
	T_NUM NUMBER,
	T_INT INTEGER,
	T_SINT SMALLINT,
	T_BFLOAT BINARY_FLOAT,
	T_FLOAT FLOAT,
	T_DOUBLE BINARY_DOUBLE,
	T_REAL REAL,
	T_DATE DATE,
	T_DECIMAL DECIMAL,
	T_TS TIMESTAMP,
	T_VCHAR VARCHAR(100),
	T_CHAR CHAR(100),
	T_NCHAR NCHAR(100),
	T_VCHAR2 VARCHAR2(100),
	T_NVCHAR NVARCHAR2(100),
	T_BLOB BLOB,
	T_CLOB CLOB,
	T_NCLOB NCLOB,
	T_RAW RAW(100),
	T_LR LONG RAW
);

INSERT INTO TEST.SRC (T_NUM,T_INT,T_SINT,T_BFLOAT,T_FLOAT,T_DOUBLE,T_REAL,T_DATE,T_DECIMAL,T_TS,T_VCHAR,T_CHAR,T_NCHAR,T_VCHAR2,T_NVCHAR,T_BLOB,T_CLOB,T_NCLOB,T_RAW,T_LR) VALUES (123,123,122,1.2,1.2,1.2,1.2,TIMESTAMP'2022-01-01 01:01:01',12.3,TIMESTAMP'2022-01-01 01:01:01','12','12','12','12','12',HEXTORAW(''20''),TO_CLOB('12'),TO_CLOB('2'),'20','3132');
INSERT INTO TEST.DEST
(T_NUM, T_INT, T_SINT, T_BFLOAT, T_FLOAT, T_DOUBLE, T_REAL, T_DATE, T_DECIMAL, T_TS, T_VCHAR, T_CHAR, T_NCHAR, T_VCHAR2, T_NVCHAR, T_BLOB, T_CLOB, T_NCLOB, T_RAW, T_LR)
VALUES(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
