{
 "title": "go-etl",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "total record",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "datax_channel_total_record{job=\"etl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total byte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "datax_channel_total_byte{job=\"etl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate record",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(datax_channel_total_record{job=\"etl\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate byte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(datax_channel_total_byte{job=\"etl\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "channel_record",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "datax_channel_record{job=\"etl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "channel_byte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "datax_channel_byte{job=\"etl\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}